20180611

이번주 React Router에 대해서 수업 진행됨.

## 예외처리

프로그램의 언어들이 항상 완벽하게 동작하지는 않는다.  
단순 버그이거나, 프로그래머가 잘못 작성했거나, 프로그래밍 언어 자체가 에러를 내는 경우가 있다.

### 1. 동기식 코드에서의 예외 처리

프론트엔드 개발자의 실수
```js
new Array(-1) // RangeError: Invalid array length
```
```js
console.log(foo) // ReferenceError: foo is not defined
```

프론트엔드 개발자의 의도와 다른 실수
```js
fetch('https://nonexistent-domain.nowhere'); // TypeError: Failed to fetch
// 위 주소는 맞는데 서버/네트워크 쪽 에러가 있다거나
```

에러가 발생하면 나머지 로직이 실행되지 않는다. 그 시점에 실행 중이었던 작업을 완료할 수 없게 된다. 
```js
console.log('에러가 나기 직전까지의 코드는 잘 실행됩니다.');
new Array(-1); // RangeError: Invalid array length
console.log('에러가 난 이후의 코드는 실행되지 않습니다.'); // 이것은 실행되지 않는다.
```
위와 같이 코드의 실행이 중단된다.

`try...catch...finally` 구문을 사용하면 에러가 나더라도 코드의 실행을 지속할 수 있다.

```js
try {
  // 여기서 에러가 나면 에러가 난 시점에 코드의 흐름이
  // catch로 넘어간다.
  console.log('에러가 나기 직전까지의 코드는 잘 실행됩니다.');
  new Array(-1); // RangeError: Invalid array length
  console.log('에러가 난 이후의 코드는 실행되지 않습니다.');
} catch (e) {
  console.log('코드의 실행 흐름이 catch 블록으로 옮겨집니다.');
  alert(`다음과 같은 에러가 발생했습니다: ${e.name}: ${e.message}`);
}
```

+ `try`: 에러가 났을 때 원상복구를 시도할 코드. 에러 발생시 코드의 실행 흐름이 `catch` 블록으로 옮겨간다.
+ `catch`: 에러에 대한 정보를 담고 있는 객체(위 예제의 `e`)를 사용할 수 있다.
  - `e.name`: `RangeError`같은 에러의 이름
  - `e.meassage`: `Invalid array length` 에러 메시지
  - ```js
    try {
      console.log('에러가 나기 직전까지의 코드는 잘 실행됩니다.');
      /* new Array(-1); */
      console.log(foo);
      console.log('에러가 난 이후의 코드는 실행되지 않습니다.');
    } catch (e) {
      if(e.name === 'RangeError') {
        alert(`배열 생성자에 잘못된 인수가 입력되었습니다.`)
      } else if (e.name === `ReferenceError`) {
        alert(`선언되지 않은 변수가 사용되고 있습니다.`)
      }
      console.log('코드의 실행 흐름이 catch 블록으로 옮겨집니다.');
    }
    ```
+ `finally`: `try`블록 안에서의 에러 발생 여부와 관계 없이 무조건 실행되어야 하는 코드  
`return`, `break`, `continue`등으로 코드의 실행 흐름이 즉시 이동되더라도 실행된다.
  ```js
  for (let i of [1, 2, 3]) {
    try {
      if (i === 3) {
        break;
      }
    } finally {
      console.log(`현재 i의 값: ${i}`);
    }
  }
  ```
  - `finally`블록은 catch 블록과도 같이 사용된다.
    * 에러가 안 났을 때: **try - finally**
    * 에러가 났을 때: **try - 에러발생 - catch - finally**


#### 1-1. 직접 에러 발생시키기

코드를 다른 사람이나 미래의 내가 의도한 대로 사용하지 않을 경우 에러가 발생하도록 할 수 있다.

**`Error`생성자, `throw`구문**
```js
const even = parseInt(prompt('짝수를 입력하세요'));
if (even % 2 !== 0) {
  throw new Error('짝수가 아닙니다.');
}
// 3을 입력할 경우
// Error: 짝수가 아닙니다.
```
```js
throw 'ggg';
// 던지는 것에 제한이 없으나
throw new Error('ddd')
// 반드시 에러 객체를 던져야 한다.

const e = new Error('짝수가 아니다')
// Error는 어디서나 쓸 수 있는 객체(생성자)이다.
e;
// Error: 짝수가 아니다.
```

다음과 같이 내가 에러를 만들어 던질 수 있고, 이를 `try...catch` 구문으로 잡을 수 있다.
```js
try {
  const even = parseInt(prompt('짝수를 입력하세요'));
  if (even % 2 !== 0) {
    throw new Error('짝수가 아닙니다.');
  }
} catch (e) {
  alert(e.message);
}
```

복잡한 프로그램을 짜다보면 추가적인 자세한 정보를 추가해서 에러를 만들고 싶게 된다.  
에러의 종류를 구분해야 하거나 에러 객체에 기능을 추가해야 할 필요가 있다.

그냥 내장 에러 생성자가 아니라 내가 자체 Error 클래스를 만들경우 다음과 같은 방법이 있다.
```js
class MyError extends Error {
  constructor(value, ...params) {
    super(...params);
    this.value = value;
    this.name = 'MyError';
  }
}

try {
  const even = parseInt(prompt('짝수를 입력하세요'));
  if (even % 2 !== 0) {
    throw new MyError(even, '짝수가 아닙니다.');
  }
} catch (e) {
  if (e instanceof MyError) {
    console.log(`${e.name}: ${e.value} 는 ${e.message}`);
  }
}
```

에러에서도 동기식 처리와 비동기식 처리가 있다.

### 2. 비동기식 코드에서의 예외 처리

#### 2-1. 비동기 콜백

비동기식으로 작동하는 콜백의 내부에서 발생한 에러는, 콜백 바깥에 있는 try 블록으로는 잡아낼 수 없다.
```js
try {
  setTimeout(() => {
    // 비동기 코드 안의 에러는 잡히지 않는다.
    throw new Error('에러!');
  });
} catch (e) {
  console.error(e);
}
// Uncaught Error: 에러!
// 에러가 잡히지 않아서 생기는 에러;;
```

JavaScript 엔진은 에러가 발생하는 순간 호출 스택을 되감는 과정을 거친다.   
이 과정 중에 `try` 블록을 만나야 코드의 실행 흐름을 원상복구시킬 수 있다.

**에러는 호출스택과 관련되어 있다.**  

아래는 동기식 예외 발생
```js
function add(x, y) {
  // 에러를 이곳에서 발생시키고
  new Array(-1);
  return x + y;
}

function add2(x) {
  return add(x, 2);
}

function add2AndPrint(x) {
  // try... catch 구문이 여기있지만
  // 자바스크립트 실행 엔진이 에러가 발생하면 호출 스택을 하나씩 지워가면서 
  // try가 있는지 찾아본다.
  try {
    // 여기서 add2를 호출하고 add2는 add를 호출하기 때문에 에러가 잡힌다.
    const result = add2(x);
    console.log(result);
  } catch(e) {
    alert('잡았다!');
  }
}

add2AndPrint(3); // alert으로 '잡았다!'가 뜬다.
```

```js
function add(x, y) {
  // 에러를 이곳에서 발생시키고
  new Array(-1);
  return x + y;
}

function add2(x) {
  // 호출스택을 되감다 가장 먼저 만나는 try에서 에러가 잡힌다.
  try {
    return add(x, 2);
  } catch(e) {
    alert('add2에서 잡히나?')
  }
}

function add2AndPrint(x) {
  try {
    const result = add2(x);
    console.log(result);
  } catch(e) {
    alert('잡았다!');
  }
}

add2AndPrint(3); // alert으로 'add2에서 잡히나?'가 뜬다.
```

비동기 콜백이라면 단순 `try...catch` 구문으로는 잡을 수 없다.  
비동기 콜백이 실행될 때는 이미 호출스택이 비워져 `try`를 찾을 수 없다.
```js
function add(x, y) {
  setTimeout(() => {
    // 이 콜백이 일단 태스크큐에 들어갔다가 호출 스택이 비워지면 실행된다.
    // 호출스택을 되감아 가면서 try를 찾아야하는데
    // 이 콜백이 실행될 때는 이미 호출스택이 비워졌으므로 try를 찾을 수 없다.
    new Array(-1);
  })
  return x + y;
}

function add2(x) {
  try {
    return add(x, 2);
  } catch(e) {
    alert('add2에서 잡히나?')
  }
}

function add2AndPrint(x) {
  try {
    const result = add2(x);
    console.log(result);
  } catch(e) {
    alert('잡았다!');
  }
}

add2AndPrint(3);
```

따라서, 비동기 콜백 내부에 `try`를 작성해주어야 한다.

[이벤트 리스너와 try catch 블록 예제](https://codepen.io/dbeat999/pen/bKqdwW)
```js
const buttonEl = document.querySelector('button');

try {
  buttonEl.addEventListener('click', e => {
    try {
      new Array(-1);
      alert('버튼이 눌렸습니다.');      
    } catch (e) {
      alert('이벤트 리스너 안에서 에러가 발생했습니다.');
    }
  })  
} catch (e) {
  alert('에러가 발생했습니다.'); // 출력되지 않음
}
```

#### 2-2. Pomise

Promise 객체는 세 가지 상태를 가질 수 있다.

+ pending - Promise 객체에 결과값이 채워지지 않은 상태
+ fulfilled - Promise 객체에 결과값이 채워진 상태(이때 `then`메소드 또는 `await`를 통해 무언가를 실행했다.)
+ **rejected - Promise 객체에 결과값을 채우려고 시도하다가 에러가 난 상태**
  - `then`메소드에 첫 번째 인수로 넘겨준 콜백이 실행되지 않고, **두 번째 인수로 넘겨준 콜백이 실행된다.** 그리고 이 콜백에는 **에러 객체가 첫번째 인수로 주어진다.**

```js
const p = new Promise(resolve => {
  const even = parseInt(prompt('짝수를 입력하세요'));
  if (even % 2 !== 0) {
    throw new Error('짝수가 아닙니다.');
  } else {
    // 짝수면 fullfiled되어 then메소드의 첫번째 인수로 들어간 함수가 실행
    resolve(even);
  }
});

// then 콜백에서 반환된 값이 다음Promise의 값이 된다.
p.then(even => {
  return '짝수입니다.';
}, e => {
  return e.message;
}).then(alert);
// .then(msg => alert(msg))와 같음
```
`Promise`가 rejected 상태가 되었을 때 `catch` 메소드를 통해 다음과 같은 방법으로도 에러 처리 콜백을 지정해 줄 수 있다.
```js
p.then(even => {
  return '짝수입니다.';
}).catch(e => {
  return e.message;
}).then(alert);
```

#### 2-3. 비동기 함수

비동기 코드에서의 `try...catch`와 비동기 함수에서의 `try...catch`는 다르게 동작한다. (내부 동작 방식이 완전히 다르다. - 비동기 함수를 사용하면 예외처리도 보다 편하게 할 수 있다.)

비동기 함수 내부에서는, rejected 상태가 된 `Promise`객체를 동기식 예외처리 방식과 동일하게 `try...catch...finally` 구문으로 처리할 수 있다.
```js
async function func() {
  try {
    // ※ 단, Promise 객체에 대해 await 구문을 사용해야만 
    // 에러가 발생했을 때 catch 블록으로 코드의 실행 흐름이 이동한다.
    const res = await fetch('https://nonexistent-domain.nowhere');
  } catch (e) {
    console.log(e.message);
  }
}

func(); // 출력 결과: Failed to fetch
```

---

## 모듈

큰 규모의 프로젝트에서 JavaScript 코드를 여러 파일과 폴더에 나누어 작성하고, 충돌하지 않게 서로가 서로를 효율적으로 불러올 수 있도록 해주는 시스템이 필요해졌다.

ES2015 모듈: `script`태그에 `type="module"` 어트리뷰트 추가
```HTML
<!-- 모듈로서 동작한다, 파일 확장자는 대개 .mjs -->
<script type="module" src="index.mjs"></script>
```
단, 다음과 같은 이유로 아직 브라우저에 내장된 모듈 기능을 사용하는 경우가 별로 없다.
+ 이전까지의 JavaScript 파일의 동작방식과 다른 동작방식을 가지고 있다.  
+ 모듈이 제대로 동작하기 위해 [몇가지 조건을 충족시켜야 한다.](https://jakearchibald.com/2017/es-modules-in-browsers/)
+ 구형 브라우저는 모듈을 지원하지 않는다.

대신 Webpack, Parcel 등의 모듈번들러를 통해 변환과정을 거친 뒤, 브라우저에서 일반적인 JavaScript파일로 불러오는 방법이 널리 사용되고 있는 추세이다.

모듈 번들러는 여러 자바스크립트 파일을 설정에 따라 하나 이상의 파일로 합쳐주는 프로그램이다. 최신문법을 트랜스파일링 해주는 기능까지 갖추고 있다.

모듈 번들러들은 파일간 관계를(의존성) 분석해서 모듈을 하나로 합쳐줄 때 사용하는 방식이 각자 다르다.
+ Webpack은 `import`를 통해 분석한다.
+ Parcel은 html 태그를 보고도 분석한다.(html 안에 link태그 쓰고, scss를 불러오는 식으로 쓸 수 있다.)

### 1. 모듈이란? 

ES2015 모듈: JavaScript코드를 담고 있는 파일  

+ `import` 혹은 `export`구문을 사용할 수 있다.
+ 기본으로 엄격모드로 동작한다.
+ 모듈 파일의 가장 바깥쪽에서 선언된 이름은 전역 스코프가 아니라 **모듈 스코프에서 선언된다.**

### 2. 모듈 스코프

```js
// variables.js
var foo = 'bar';

// 이 파일이 모듈로서 사용되고 있다면, `undefined`가 출력된다.
console.log(window.foo);
```

이 모듈스코프는 모듈 파일마다 개별적으로 존재한다.

따라서 여러 모듈의 가장 바깥쪽에서 같은 이름으로 변수, 함수, 클래스를 선언하더라도,   
서로 다른 스코프에서 선언되기 때문에 이름의 충돌이 생길 일이 없다.

### 3. export & import

값이 아니라 이름이 export되는 것

+ 모듈 스코프에서 정의된 이름은 export 구문을 통해 다른 파일에서 사용할 수 있다.
  - variables.js
    ```js
    const foo = 'bar';
    const spam = 'eggs';

    export {foo, spam};
    ```
  - functions.js
    ```js
    import {foo, spam} from './variables.js';

    console.log(foo);
    console.log(spam);
    ````
+ 함수나 클래스도 export를 통해 여러 모듈에서 재사용할 수 있다.
  ```js
  function add(x, y) {
    return x + y;
  }
  class Person {
    // ...
  }

  export { add, Person };
  ```
+ 다른 모듈에 있는 이름을 사용하려면, 반드시 모듈에서 이름을 export 해주어야 한다.  
모듈 실행환경에 따라 에러나, 이름에 `undefined`가 들어가는 식으로 의도치 않게 동작한다.

### 4. 선언과 동시에 export 하기

이름을 선언하는 구문 앞에 export를 붙여주면, 선언과 export를 한꺼번에 할 수 있다.
```js
export const foo = 'bar';
export function add(x, y) {
  return x + y;
}
export class Person {
  // ...
}
```

### 5. default export

모듈을 대표하는 하나의 **값**을 지정하고, 그 값을 다른 모듈에서 편하게 불러와서 사용할 수 있다.  
이렇게 사용하는 값을 **default export**라고 부른다.
+ foo.js
  ```js
  export default 'bar';
  ```
+ main.js
  ```js
  // 중괄호를 생략하면, 모듈의 default export를 가져온다.
  import foo from './foo.js'

  console.log(foo); // bar
  ```

※ 모듈당 하나의 default export밖에 허용되지 않는다.  
모듈에는 하나의 default export와 여러개의 named export(일반적인 export)를 지정할 수 있다.

import 구문에서 default export와 일반적인 export를 동시에 가져올 수 있다.
```js
                        // node_modules에 설치된 것은 따로 path없이 불러오면 됨
import React, {Component, Fragament} from 'react';
```

```js
export default class React {}
export class Componet { /*...*/ }
export class Fragment { /*...*/ }
```

### 6. 다름 이름으로 export & import 하기

`export`혹은 `import` 하는 이름의 뒤에 `as`를 붙여 다른 이름이 대신 사용되게 할 수 있다.
+ export 이름 뒤에 as
  - foo.js
  ```js
  const foo = 'bar';
  export {foo as FOO};
  ```
  - main.js
  ```js
  import {FOO} from './foo.js'
  ```
+ import 이름 뒤에 as
  - foo.js
  ```js
  const foo = 'bar';
  export foo;
  ```
  - main.js
  ```js
  import {foo as FOO} from './foo.js'
  console.log(FOO)
  ```

### 7. 모듈 사용 시 주의할 점

모듈 번들러는 import를 하지 않으면 아예 JavaScript코드를 실행시키지 않는다.  
모듈간의 의존관계를 다 파악한 뒤 필요한 것만 실행시킨다.

log.js
```js
console.log('log~~~~~')
export const foo = bar;
```
main.js
```js
import {foo} from './log'

// log~~~~가 콘솔에 출력된다.
```

만약 다른 모듈에서도 'log.js'를 `import` 하더라도 'log~~~~'는 한번만 출력된다.  
이는 `import`구문이 코드를 실행시키라는 명령이 아니기 때문이다.  
`export`와 `import` 구문은 단지 모듈간의 의존관계를 나타내는 것일 뿐이다.

ECMAScript 공식 명세에는 모듈을 불러오는 방법에 대한 내용이 포함되어 있지 않다.  
모듈번들러, 브라우저마다 모듈을 불러오는 방법이나 구체적인 동작 방식은 다를 수 있다.

### 8. ES2015 이전의 모듈들

[ES2015 모듈 이전에 CommonJS, AMD 등의 모듈 시스템이 있었다.](https://d2.naver.com/helloworld/12864)

```js
// Node.js에서 쓰는 모듈 객체
const os = require('os')
module.export = {
  a: a
  b: b
}
```

---

## 리액트 실습

[create-react-app에서 환경변수를 사용하는 방법](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-custom-environment-variables)

지금은 prompt를 사용해 입력 UI 구성, 나중에 Ref, Context등의 고급 기능 배움

※ 서로의 역할과 책임에 맞는 코드만 작성해주는 것이 좋다.

상태관리에 대해 이번주 Context 다음주 Redux를 배우고 프로젝트에 사용할 것이다.

상태관리에 쓰이는 기술들
+ Context
+ Redux
+ MobX

### 1. React.Fragment

[리액트 Fragment](http://reactjs-org-ko.netlify.com/docs/fragments.html)

컴포넌트 클래스의 render 메소드에서 리턴하는 엘리먼트들은 별도의 엘리먼트(예를 들어 `<div>`)로 감싸줘야만 한다.

리액트의 Fragment를 사용하면 DOM에 별도의 노드를 추가하지 않고 자식 목록을 그룹화 할 수 있다.
```js
render() {
  return {
    <React.Fragement>
      <Component1/>
      <Component2/>
      <Component3/>
    </React.Fragement>
  }
}
```
## 2. Today I fonund out

리액트 컴포넌트 간의 변경사항 공유 때문에 조상 컴포넌트에서 상태를 관리하니까 컴포넌트를 나눌때마다 상태도 내려보내줘야해서 헷갈린다. Redux나 Context를 통해서 관리가 가능하다는데, 어떤식으로 만들었길래 그게 가능할까 신기하다.  
역할과 책임은 만들때마다 고민된다. 정답이 있는 건 아닌것 같은데 어떻게 코드를 짜야 역할과 책임에 맞게 코드를 작성하게 되는 건지 아직은 감이 잡히지 않는다. 많이 만들어봐야겠다.